// Ported 1:1 from Guacamole 1.6 guacamole-server src/protocols/rdp/keymaps: the "en-us-qwerty"
// keymap and its parent "base" (generated the same way guacd's generate.pl builds
// _generated_keymaps.c). Each entry is a guac_rdp_keysym_desc: the X11 keysym, the RDP scancode
// that produces it, whether that scancode is EXTENDED (0xE0 prefix), and the modifier/lock state the
// scancode requires (set*/clear*). The en-US pin (WASM keyboard_layout=0x409) is why THIS keymap is
// the one loaded: every scancode is interpreted by the guest as en-US, so reproducing a character
// means sending the en-US scancode + Shift the character needs -- correct for every client layout and,
// unlike a Unicode injection, correct in terminals. Modifier/lock flag values match keymap.h:
//   MOD_SHIFT=1, MOD_ALTGR=2 ; LOCK_SCROLL=1, LOCK_NUM=2, LOCK_CAPS=4, LOCK_KANA=8.
// base_altgr is deliberately NOT included (en-us-qwerty's parent is "base"): the en-US guest has no
// AltGr layer, so AltGr keysyms are undefined here and are dropped by the server half -- which is
// exactly how Guacamole types AltGr characters on an en-US-pinned guest.

export const MOD_SHIFT = 1;
export const MOD_ALTGR = 2;

export const LOCK_SCROLL = 1;
export const LOCK_NUM = 2;
export const LOCK_CAPS = 4;
export const LOCK_KANA = 8;

// X11 keysyms of the modifier and lock keys (keymap.h GUAC_RDP_KEYSYM_*).
export const KEYSYM_LSHIFT = 0xffe1;
export const KEYSYM_RSHIFT = 0xffe2;
export const KEYSYM_LCTRL = 0xffe3;
export const KEYSYM_RCTRL = 0xffe4;
export const KEYSYM_LALT = 0xffe9;
export const KEYSYM_RALT = 0xffea;
export const KEYSYM_ALTGR = 0xfe03;
export const KEYSYM_CAPS_LOCK = 0xffe5;
export const KEYSYM_NUM_LOCK = 0xff7f;
export const KEYSYM_SCROLL_LOCK = 0xff14;
export const KEYSYM_KANA_LOCK = 0xff2d;

export interface KeysymDesc {
    keysym: number;
    scancode: number;
    extended?: boolean;
    setMod?: number;
    clearMod?: number;
    setLocks?: number;
    clearLocks?: number;
}

// The RDP scancode as the 16-bit value expected by DeviceEvent.keyPressed/keyReleased: an extended key
// carries 0xE000 in its high bits (Scancode::from_u16 in ironrdp-input reads that as the EXTENDED flag).
export function keysymScancode(desc: KeysymDesc): number {
    return desc.extended === true ? 0xe000 | desc.scancode : desc.scancode;
}

export const EN_US_QWERTY_KEYMAP: readonly KeysymDesc[] = [
    { keysym: 0x20, scancode: 0x39 },
    { keysym: 0xff09, scancode: 0xf },
    { keysym: 0xff08, scancode: 0xe },
    { keysym: 0xff0d, scancode: 0x1c },
    { keysym: 0xff1b, scancode: 0x1 },
    { keysym: 0xff63, scancode: 0x52, extended: true },
    { keysym: 0xffff, scancode: 0x53, extended: true },
    { keysym: 0xff50, scancode: 0x47, extended: true },
    { keysym: 0xff57, scancode: 0x4f, extended: true },
    { keysym: 0xff51, scancode: 0x4b, extended: true },
    { keysym: 0xff52, scancode: 0x48, extended: true },
    { keysym: 0xff53, scancode: 0x4d, extended: true },
    { keysym: 0xff54, scancode: 0x50, extended: true },
    { keysym: 0xff55, scancode: 0x49, extended: true },
    { keysym: 0xff56, scancode: 0x51, extended: true },
    { keysym: 0xff61, scancode: 0x37, extended: true },
    { keysym: 0xff7f, scancode: 0x45 },
    { keysym: 0xff14, scancode: 0x46 },
    { keysym: 0xffe5, scancode: 0x3a },
    { keysym: 0xffb0, scancode: 0x52, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb1, scancode: 0x4f, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb2, scancode: 0x50, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb3, scancode: 0x51, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb4, scancode: 0x4b, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb5, scancode: 0x4c, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb6, scancode: 0x4d, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb7, scancode: 0x47, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb8, scancode: 0x48, clearMod: 1, setLocks: 2 },
    { keysym: 0xffb9, scancode: 0x49, clearMod: 1, setLocks: 2 },
    { keysym: 0xffaa, scancode: 0x37 },
    { keysym: 0xffab, scancode: 0x4e },
    { keysym: 0xffad, scancode: 0x4a },
    { keysym: 0xffae, scancode: 0x53 },
    { keysym: 0xffaf, scancode: 0x35, extended: true },
    { keysym: 0xffbe, scancode: 0x3b },
    { keysym: 0xffbf, scancode: 0x3c },
    { keysym: 0xffc0, scancode: 0x3d },
    { keysym: 0xffc1, scancode: 0x3e },
    { keysym: 0xffc2, scancode: 0x3f },
    { keysym: 0xffc3, scancode: 0x40 },
    { keysym: 0xffc4, scancode: 0x41 },
    { keysym: 0xffc5, scancode: 0x42 },
    { keysym: 0xffc6, scancode: 0x43 },
    { keysym: 0xffc7, scancode: 0x44 },
    { keysym: 0xffc8, scancode: 0x57 },
    { keysym: 0xffc9, scancode: 0x58 },
    { keysym: 0xffe1, scancode: 0x2a },
    { keysym: 0xffe2, scancode: 0x36 },
    { keysym: 0xffe3, scancode: 0x1d },
    { keysym: 0xffe4, scancode: 0x1d, extended: true },
    { keysym: 0xffe9, scancode: 0x38 },
    { keysym: 0xffea, scancode: 0x38, extended: true },
    { keysym: 0xffe7, scancode: 0x5b, extended: true },
    { keysym: 0xffe8, scancode: 0x5c, extended: true },
    { keysym: 0xffeb, scancode: 0x5b, extended: true },
    { keysym: 0xffec, scancode: 0x5c, extended: true },
    { keysym: 0xff67, scancode: 0x5d, extended: true },
    { keysym: 0x60, scancode: 0x29, clearMod: 1, clearLocks: 4 },
    { keysym: 0x31, scancode: 0x2, clearMod: 1, clearLocks: 4 },
    { keysym: 0x32, scancode: 0x3, clearMod: 1, clearLocks: 4 },
    { keysym: 0x33, scancode: 0x4, clearMod: 1, clearLocks: 4 },
    { keysym: 0x34, scancode: 0x5, clearMod: 1, clearLocks: 4 },
    { keysym: 0x35, scancode: 0x6, clearMod: 1, clearLocks: 4 },
    { keysym: 0x36, scancode: 0x7, clearMod: 1, clearLocks: 4 },
    { keysym: 0x37, scancode: 0x8, clearMod: 1, clearLocks: 4 },
    { keysym: 0x38, scancode: 0x9, clearMod: 1, clearLocks: 4 },
    { keysym: 0x39, scancode: 0xa, clearMod: 1, clearLocks: 4 },
    { keysym: 0x30, scancode: 0xb, clearMod: 1, clearLocks: 4 },
    { keysym: 0x2d, scancode: 0xc, clearMod: 1, clearLocks: 4 },
    { keysym: 0x3d, scancode: 0xd, clearMod: 1, clearLocks: 4 },
    { keysym: 0x71, scancode: 0x10, clearMod: 1, clearLocks: 4 },
    { keysym: 0x77, scancode: 0x11, clearMod: 1, clearLocks: 4 },
    { keysym: 0x65, scancode: 0x12, clearMod: 1, clearLocks: 4 },
    { keysym: 0x72, scancode: 0x13, clearMod: 1, clearLocks: 4 },
    { keysym: 0x74, scancode: 0x14, clearMod: 1, clearLocks: 4 },
    { keysym: 0x79, scancode: 0x15, clearMod: 1, clearLocks: 4 },
    { keysym: 0x75, scancode: 0x16, clearMod: 1, clearLocks: 4 },
    { keysym: 0x69, scancode: 0x17, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6f, scancode: 0x18, clearMod: 1, clearLocks: 4 },
    { keysym: 0x70, scancode: 0x19, clearMod: 1, clearLocks: 4 },
    { keysym: 0x5b, scancode: 0x1a, clearMod: 1, clearLocks: 4 },
    { keysym: 0x5d, scancode: 0x1b, clearMod: 1, clearLocks: 4 },
    { keysym: 0x5c, scancode: 0x2b, clearMod: 1, clearLocks: 4 },
    { keysym: 0x61, scancode: 0x1e, clearMod: 1, clearLocks: 4 },
    { keysym: 0x73, scancode: 0x1f, clearMod: 1, clearLocks: 4 },
    { keysym: 0x64, scancode: 0x20, clearMod: 1, clearLocks: 4 },
    { keysym: 0x66, scancode: 0x21, clearMod: 1, clearLocks: 4 },
    { keysym: 0x67, scancode: 0x22, clearMod: 1, clearLocks: 4 },
    { keysym: 0x68, scancode: 0x23, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6a, scancode: 0x24, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6b, scancode: 0x25, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6c, scancode: 0x26, clearMod: 1, clearLocks: 4 },
    { keysym: 0x3b, scancode: 0x27, clearMod: 1, clearLocks: 4 },
    { keysym: 0x27, scancode: 0x28, clearMod: 1, clearLocks: 4 },
    { keysym: 0x7a, scancode: 0x2c, clearMod: 1, clearLocks: 4 },
    { keysym: 0x78, scancode: 0x2d, clearMod: 1, clearLocks: 4 },
    { keysym: 0x63, scancode: 0x2e, clearMod: 1, clearLocks: 4 },
    { keysym: 0x76, scancode: 0x2f, clearMod: 1, clearLocks: 4 },
    { keysym: 0x62, scancode: 0x30, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6e, scancode: 0x31, clearMod: 1, clearLocks: 4 },
    { keysym: 0x6d, scancode: 0x32, clearMod: 1, clearLocks: 4 },
    { keysym: 0x2c, scancode: 0x33, clearMod: 1, clearLocks: 4 },
    { keysym: 0x2e, scancode: 0x34, clearMod: 1, clearLocks: 4 },
    { keysym: 0x2f, scancode: 0x35, clearMod: 1, clearLocks: 4 },
    { keysym: 0x7e, scancode: 0x29, setMod: 1, clearLocks: 4 },
    { keysym: 0x21, scancode: 0x2, setMod: 1, clearLocks: 4 },
    { keysym: 0x40, scancode: 0x3, setMod: 1, clearLocks: 4 },
    { keysym: 0x23, scancode: 0x4, setMod: 1, clearLocks: 4 },
    { keysym: 0x24, scancode: 0x5, setMod: 1, clearLocks: 4 },
    { keysym: 0x25, scancode: 0x6, setMod: 1, clearLocks: 4 },
    { keysym: 0x5e, scancode: 0x7, setMod: 1, clearLocks: 4 },
    { keysym: 0x26, scancode: 0x8, setMod: 1, clearLocks: 4 },
    { keysym: 0x2a, scancode: 0x9, setMod: 1, clearLocks: 4 },
    { keysym: 0x28, scancode: 0xa, setMod: 1, clearLocks: 4 },
    { keysym: 0x29, scancode: 0xb, setMod: 1, clearLocks: 4 },
    { keysym: 0x5f, scancode: 0xc, setMod: 1, clearLocks: 4 },
    { keysym: 0x2b, scancode: 0xd, setMod: 1, clearLocks: 4 },
    { keysym: 0x51, scancode: 0x10, setMod: 1, clearLocks: 4 },
    { keysym: 0x57, scancode: 0x11, setMod: 1, clearLocks: 4 },
    { keysym: 0x45, scancode: 0x12, setMod: 1, clearLocks: 4 },
    { keysym: 0x52, scancode: 0x13, setMod: 1, clearLocks: 4 },
    { keysym: 0x54, scancode: 0x14, setMod: 1, clearLocks: 4 },
    { keysym: 0x59, scancode: 0x15, setMod: 1, clearLocks: 4 },
    { keysym: 0x55, scancode: 0x16, setMod: 1, clearLocks: 4 },
    { keysym: 0x49, scancode: 0x17, setMod: 1, clearLocks: 4 },
    { keysym: 0x4f, scancode: 0x18, setMod: 1, clearLocks: 4 },
    { keysym: 0x50, scancode: 0x19, setMod: 1, clearLocks: 4 },
    { keysym: 0x7b, scancode: 0x1a, setMod: 1, clearLocks: 4 },
    { keysym: 0x7d, scancode: 0x1b, setMod: 1, clearLocks: 4 },
    { keysym: 0x7c, scancode: 0x2b, setMod: 1, clearLocks: 4 },
    { keysym: 0x41, scancode: 0x1e, setMod: 1, clearLocks: 4 },
    { keysym: 0x53, scancode: 0x1f, setMod: 1, clearLocks: 4 },
    { keysym: 0x44, scancode: 0x20, setMod: 1, clearLocks: 4 },
    { keysym: 0x46, scancode: 0x21, setMod: 1, clearLocks: 4 },
    { keysym: 0x47, scancode: 0x22, setMod: 1, clearLocks: 4 },
    { keysym: 0x48, scancode: 0x23, setMod: 1, clearLocks: 4 },
    { keysym: 0x4a, scancode: 0x24, setMod: 1, clearLocks: 4 },
    { keysym: 0x4b, scancode: 0x25, setMod: 1, clearLocks: 4 },
    { keysym: 0x4c, scancode: 0x26, setMod: 1, clearLocks: 4 },
    { keysym: 0x3a, scancode: 0x27, setMod: 1, clearLocks: 4 },
    { keysym: 0x22, scancode: 0x28, setMod: 1, clearLocks: 4 },
    { keysym: 0x5a, scancode: 0x2c, setMod: 1, clearLocks: 4 },
    { keysym: 0x58, scancode: 0x2d, setMod: 1, clearLocks: 4 },
    { keysym: 0x43, scancode: 0x2e, setMod: 1, clearLocks: 4 },
    { keysym: 0x56, scancode: 0x2f, setMod: 1, clearLocks: 4 },
    { keysym: 0x42, scancode: 0x30, setMod: 1, clearLocks: 4 },
    { keysym: 0x4e, scancode: 0x31, setMod: 1, clearLocks: 4 },
    { keysym: 0x4d, scancode: 0x32, setMod: 1, clearLocks: 4 },
    { keysym: 0x3c, scancode: 0x33, setMod: 1, clearLocks: 4 },
    { keysym: 0x3e, scancode: 0x34, setMod: 1, clearLocks: 4 },
    { keysym: 0x3f, scancode: 0x35, setMod: 1, clearLocks: 4 },
    { keysym: 0x60, scancode: 0x29, clearMod: 1, setLocks: 4 },
    { keysym: 0x31, scancode: 0x2, clearMod: 1, setLocks: 4 },
    { keysym: 0x32, scancode: 0x3, clearMod: 1, setLocks: 4 },
    { keysym: 0x33, scancode: 0x4, clearMod: 1, setLocks: 4 },
    { keysym: 0x34, scancode: 0x5, clearMod: 1, setLocks: 4 },
    { keysym: 0x35, scancode: 0x6, clearMod: 1, setLocks: 4 },
    { keysym: 0x36, scancode: 0x7, clearMod: 1, setLocks: 4 },
    { keysym: 0x37, scancode: 0x8, clearMod: 1, setLocks: 4 },
    { keysym: 0x38, scancode: 0x9, clearMod: 1, setLocks: 4 },
    { keysym: 0x39, scancode: 0xa, clearMod: 1, setLocks: 4 },
    { keysym: 0x30, scancode: 0xb, clearMod: 1, setLocks: 4 },
    { keysym: 0x2d, scancode: 0xc, clearMod: 1, setLocks: 4 },
    { keysym: 0x3d, scancode: 0xd, clearMod: 1, setLocks: 4 },
    { keysym: 0x51, scancode: 0x10, clearMod: 1, setLocks: 4 },
    { keysym: 0x57, scancode: 0x11, clearMod: 1, setLocks: 4 },
    { keysym: 0x45, scancode: 0x12, clearMod: 1, setLocks: 4 },
    { keysym: 0x52, scancode: 0x13, clearMod: 1, setLocks: 4 },
    { keysym: 0x54, scancode: 0x14, clearMod: 1, setLocks: 4 },
    { keysym: 0x59, scancode: 0x15, clearMod: 1, setLocks: 4 },
    { keysym: 0x55, scancode: 0x16, clearMod: 1, setLocks: 4 },
    { keysym: 0x49, scancode: 0x17, clearMod: 1, setLocks: 4 },
    { keysym: 0x4f, scancode: 0x18, clearMod: 1, setLocks: 4 },
    { keysym: 0x50, scancode: 0x19, clearMod: 1, setLocks: 4 },
    { keysym: 0x5b, scancode: 0x1a, clearMod: 1, setLocks: 4 },
    { keysym: 0x5d, scancode: 0x1b, clearMod: 1, setLocks: 4 },
    { keysym: 0x5c, scancode: 0x2b, clearMod: 1, setLocks: 4 },
    { keysym: 0x41, scancode: 0x1e, clearMod: 1, setLocks: 4 },
    { keysym: 0x53, scancode: 0x1f, clearMod: 1, setLocks: 4 },
    { keysym: 0x44, scancode: 0x20, clearMod: 1, setLocks: 4 },
    { keysym: 0x46, scancode: 0x21, clearMod: 1, setLocks: 4 },
    { keysym: 0x47, scancode: 0x22, clearMod: 1, setLocks: 4 },
    { keysym: 0x48, scancode: 0x23, clearMod: 1, setLocks: 4 },
    { keysym: 0x4a, scancode: 0x24, clearMod: 1, setLocks: 4 },
    { keysym: 0x4b, scancode: 0x25, clearMod: 1, setLocks: 4 },
    { keysym: 0x4c, scancode: 0x26, clearMod: 1, setLocks: 4 },
    { keysym: 0x3b, scancode: 0x27, clearMod: 1, setLocks: 4 },
    { keysym: 0x27, scancode: 0x28, clearMod: 1, setLocks: 4 },
    { keysym: 0x5a, scancode: 0x2c, clearMod: 1, setLocks: 4 },
    { keysym: 0x58, scancode: 0x2d, clearMod: 1, setLocks: 4 },
    { keysym: 0x43, scancode: 0x2e, clearMod: 1, setLocks: 4 },
    { keysym: 0x56, scancode: 0x2f, clearMod: 1, setLocks: 4 },
    { keysym: 0x42, scancode: 0x30, clearMod: 1, setLocks: 4 },
    { keysym: 0x4e, scancode: 0x31, clearMod: 1, setLocks: 4 },
    { keysym: 0x4d, scancode: 0x32, clearMod: 1, setLocks: 4 },
    { keysym: 0x2c, scancode: 0x33, clearMod: 1, setLocks: 4 },
    { keysym: 0x2e, scancode: 0x34, clearMod: 1, setLocks: 4 },
    { keysym: 0x2f, scancode: 0x35, clearMod: 1, setLocks: 4 },
    { keysym: 0x7e, scancode: 0x29, setMod: 1, setLocks: 4 },
    { keysym: 0x21, scancode: 0x2, setMod: 1, setLocks: 4 },
    { keysym: 0x40, scancode: 0x3, setMod: 1, setLocks: 4 },
    { keysym: 0x23, scancode: 0x4, setMod: 1, setLocks: 4 },
    { keysym: 0x24, scancode: 0x5, setMod: 1, setLocks: 4 },
    { keysym: 0x25, scancode: 0x6, setMod: 1, setLocks: 4 },
    { keysym: 0x5e, scancode: 0x7, setMod: 1, setLocks: 4 },
    { keysym: 0x26, scancode: 0x8, setMod: 1, setLocks: 4 },
    { keysym: 0x2a, scancode: 0x9, setMod: 1, setLocks: 4 },
    { keysym: 0x28, scancode: 0xa, setMod: 1, setLocks: 4 },
    { keysym: 0x29, scancode: 0xb, setMod: 1, setLocks: 4 },
    { keysym: 0x5f, scancode: 0xc, setMod: 1, setLocks: 4 },
    { keysym: 0x2b, scancode: 0xd, setMod: 1, setLocks: 4 },
    { keysym: 0x71, scancode: 0x10, setMod: 1, setLocks: 4 },
    { keysym: 0x77, scancode: 0x11, setMod: 1, setLocks: 4 },
    { keysym: 0x65, scancode: 0x12, setMod: 1, setLocks: 4 },
    { keysym: 0x72, scancode: 0x13, setMod: 1, setLocks: 4 },
    { keysym: 0x74, scancode: 0x14, setMod: 1, setLocks: 4 },
    { keysym: 0x79, scancode: 0x15, setMod: 1, setLocks: 4 },
    { keysym: 0x75, scancode: 0x16, setMod: 1, setLocks: 4 },
    { keysym: 0x69, scancode: 0x17, setMod: 1, setLocks: 4 },
    { keysym: 0x6f, scancode: 0x18, setMod: 1, setLocks: 4 },
    { keysym: 0x70, scancode: 0x19, setMod: 1, setLocks: 4 },
    { keysym: 0x7b, scancode: 0x1a, setMod: 1, setLocks: 4 },
    { keysym: 0x7d, scancode: 0x1b, setMod: 1, setLocks: 4 },
    { keysym: 0x7c, scancode: 0x2b, setMod: 1, setLocks: 4 },
    { keysym: 0x61, scancode: 0x1e, setMod: 1, setLocks: 4 },
    { keysym: 0x73, scancode: 0x1f, setMod: 1, setLocks: 4 },
    { keysym: 0x64, scancode: 0x20, setMod: 1, setLocks: 4 },
    { keysym: 0x66, scancode: 0x21, setMod: 1, setLocks: 4 },
    { keysym: 0x67, scancode: 0x22, setMod: 1, setLocks: 4 },
    { keysym: 0x68, scancode: 0x23, setMod: 1, setLocks: 4 },
    { keysym: 0x6a, scancode: 0x24, setMod: 1, setLocks: 4 },
    { keysym: 0x6b, scancode: 0x25, setMod: 1, setLocks: 4 },
    { keysym: 0x6c, scancode: 0x26, setMod: 1, setLocks: 4 },
    { keysym: 0x3a, scancode: 0x27, setMod: 1, setLocks: 4 },
    { keysym: 0x22, scancode: 0x28, setMod: 1, setLocks: 4 },
    { keysym: 0x7a, scancode: 0x2c, setMod: 1, setLocks: 4 },
    { keysym: 0x78, scancode: 0x2d, setMod: 1, setLocks: 4 },
    { keysym: 0x63, scancode: 0x2e, setMod: 1, setLocks: 4 },
    { keysym: 0x76, scancode: 0x2f, setMod: 1, setLocks: 4 },
    { keysym: 0x62, scancode: 0x30, setMod: 1, setLocks: 4 },
    { keysym: 0x6e, scancode: 0x31, setMod: 1, setLocks: 4 },
    { keysym: 0x6d, scancode: 0x32, setMod: 1, setLocks: 4 },
    { keysym: 0x3c, scancode: 0x33, setMod: 1, setLocks: 4 },
    { keysym: 0x3e, scancode: 0x34, setMod: 1, setLocks: 4 },
    { keysym: 0x3f, scancode: 0x35, setMod: 1, setLocks: 4 },
];
